name: Build and publish Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Debug build context
        run: |
          echo "Working directory:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Dockerfiles:"
          find . -maxdepth 3 -iname '*dockerfile*' -print
          
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            blocknite/auckland-rubbish-scraper:latest
            blocknite/auckland-rubbish-scraper:${{ github.sha }}
